export const APP_NAME          = 'CalAI Clone'
export const APP_TAGLINE       = 'Snap your meal. Know your macros.'
export const APP_SCHEME        = 'calaiclone'
export const APP_SUPPORT_EMAIL = 'support@calaiclone.com'
export const APP_DOCS_URL      = 'https://calaiclone.com/docs'